In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder 
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
#顯示所有列
pd.set_option('display.max_columns', None)

In [3]:
train = pd.read_csv('tbrain_cc_training_48tags_hash_final.csv')

In [4]:
test = pd.DataFrame(pd.read_csv('需預測的顧客名單及提交檔案範例.csv'))
test = test.drop(columns = ['top1','top2','top3'])

In [5]:
# train_col = train.any()
# train_col

In [6]:
# 空值先補0，之後再看要補什麼，因為全部拿掉會有顧客被砍到
train = train.fillna(0)

In [7]:
train.head(5)

,dt,chid,shop_tag,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,card_1_txn_cnt,card_2_txn_cnt,card_3_txn_cnt,card_4_txn_cnt,card_5_txn_cnt,card_6_txn_cnt,card_7_txn_cnt,card_8_txn_cnt,card_9_txn_cnt,card_10_txn_cnt,card_11_txn_cnt,card_12_txn_cnt,card_13_txn_cnt,card_14_txn_cnt,card_other_txn_cnt,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card
0,1,10321418,45,3,3891.965283,3,0,0,0,1.00,0.00,0.0,0.0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1.0,99.0,30.0,95982.822967,1.0,4.0,1
1,1,10414574,15,2,10616.561549,2,0,0,0,1.00,0.00,0.0,0.0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,15.0,1.0,2.0,30.0,130702.351368,1.0,3.0,1
2,1,10134567,48,2,23527.655416,0,2,0,0,0.00,1.00,0.0,0.0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,11.0,1.0,3.0,30.0,112010.611717,0.0,4.0,1
3,1,10001003,48,9,17751.558260,7,2,0,0,0.75,0.25,0.0,0.0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,11.0,1.0,2.0,30.0,59701.507360,0.0,3.0,1
4,1,10267183,2,1,21701.307598,1,0,0,0,1.00,0.00,0.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,15.0,1.0,99.0,30.0,0.000000,0.0,6.0,0

In [8]:
train.tail(5)

,dt,chid,shop_tag,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,card_1_txn_cnt,card_2_txn_cnt,card_3_txn_cnt,card_4_txn_cnt,card_5_txn_cnt,card_6_txn_cnt,card_7_txn_cnt,card_8_txn_cnt,card_9_txn_cnt,card_10_txn_cnt,card_11_txn_cnt,card_12_txn_cnt,card_13_txn_cnt,card_14_txn_cnt,card_other_txn_cnt,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card
32975648,24,10297394,19,1,13950.944705,1,0,0,0,1.0,0.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,15.0,1.0,2.0,30.0,59701.507360,0.0,2.0,1
32975649,24,10062431,15,9,8762.298856,0,9,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,15.0,1.0,2.0,30.0,62730.806297,0.0,2.0,1
32975650,24,10062431,21,1,14209.220918,0,1,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,15.0,1.0,2.0,30.0,62730.806297,0.0,2.0,1
32975651,24,10062431,other,1,6651.116446,0,1,0,0,0.0,1.0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,15.0,1.0,2.0,30.0,62730.806297,0.0,2.0,1
32975652,24,10062431,36,22,8150.818314,22,0,0,0,1.0,0.0,0.0,0.0,0,0,0,0,0,22,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,15.0,1.0,2.0,30.0,62730.806297,0.0,2.0,1

In [9]:
# 對txn_amt、slam做Normalization，因為小數位數過大會報錯
train['txn_amt'] = (train['txn_amt'] - train['txn_amt'].min())/\
                            (train['txn_amt'].max() - train['txn_amt'].min())
train['slam'] = (train['slam'] - train['slam'].min())/\
                            (train['slam'].max() - train['slam'].min())
train.head(5)

,dt,chid,shop_tag,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,card_1_txn_cnt,card_2_txn_cnt,card_3_txn_cnt,card_4_txn_cnt,card_5_txn_cnt,card_6_txn_cnt,card_7_txn_cnt,card_8_txn_cnt,card_9_txn_cnt,card_10_txn_cnt,card_11_txn_cnt,card_12_txn_cnt,card_13_txn_cnt,card_14_txn_cnt,card_other_txn_cnt,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card
0,1,10321418,45,3,5.830816e-112,3,0,0,0,1.00,0.00,0.0,0.0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1.0,99.0,30.0,1.521183e-213,1.0,4.0,1
1,1,10414574,15,2,1.596363e-111,2,0,0,0,1.00,0.00,0.0,0.0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,15.0,1.0,2.0,30.0,2.071436e-213,1.0,3.0,1
2,1,10134567,48,2,3.541844e-111,0,2,0,0,0.00,1.00,0.0,0.0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,11.0,1.0,3.0,30.0,1.775200e-213,0.0,4.0,1
3,1,10001003,48,9,2.671485e-111,7,2,0,0,0.75,0.25,0.0,0.0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,11.0,1.0,2.0,30.0,9.461790e-214,0.0,3.0,1
4,1,10267183,2,1,3.266644e-111,1,0,0,0,1.00,0.00,0.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,15.0,1.0,99.0,30.0,0.000000e+00,0.0,6.0,0

In [10]:
# 對卡片消費次數做加總，並刪掉個別消費次數
train["sum_card_txn_cnt"] = train["card_1_txn_cnt"] + train["card_2_txn_cnt"] + train["card_3_txn_cnt"] + train["card_4_txn_cnt"] + train["card_5_txn_cnt"] + train["card_6_txn_cnt"] + train["card_7_txn_cnt"] + train["card_8_txn_cnt"] + train["card_9_txn_cnt"] + train["card_10_txn_cnt"] + train["card_11_txn_cnt"] + train["card_12_txn_cnt"] + train["card_13_txn_cnt"] + train["card_14_txn_cnt"] + train["card_other_txn_cnt"]

In [11]:
train = train.drop(columns = ['card_1_txn_cnt','card_2_txn_cnt','card_3_txn_cnt','card_4_txn_cnt','card_5_txn_cnt','card_6_txn_cnt','card_7_txn_cnt','card_8_txn_cnt','card_9_txn_cnt','card_10_txn_cnt','card_11_txn_cnt','card_12_txn_cnt','card_13_txn_cnt','card_14_txn_cnt','card_other_txn_cnt'])

In [12]:
train.head(5)

,dt,chid,shop_tag,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card,sum_card_txn_cnt
0,1,10321418,45,3,5.830816e-112,3,0,0,0,1.00,0.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,5.0,1.0,99.0,30.0,1.521183e-213,1.0,4.0,1,3
1,1,10414574,15,2,1.596363e-111,2,0,0,0,1.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,15.0,1.0,2.0,30.0,2.071436e-213,1.0,3.0,1,2
2,1,10134567,48,2,3.541844e-111,0,2,0,0,0.00,1.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,11.0,1.0,3.0,30.0,1.775200e-213,0.0,4.0,1,2
3,1,10001003,48,9,2.671485e-111,7,2,0,0,0.75,0.25,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,11.0,1.0,2.0,30.0,9.461790e-214,0.0,3.0,1,9
4,1,10267183,2,1,3.266644e-111,1,0,0,0,1.00,0.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,6.0,15.0,1.0,99.0,30.0,0.000000e+00,0.0,6.0,0,1

In [13]:
Train = train[ pd.notnull(train.shop_tag) ]
Test = train[ pd.isnull(train.shop_tag) ]

# Train.drop( ['txn_amt','slam'], axis=1, inplace=True )
# Test.drop( ['shop_tag','txn_amt','slam'], axis=1, inplace=True )

Test.drop( ['shop_tag'], axis=1, inplace=True )

Y_Train = Train.shop_tag
X_Train = Train.drop( ['shop_tag'], axis=1 )

print( f'Shape of X_Train = {X_Train.shape}' )
print( f'Shape of Y_Train = {Y_Train.shape}' )
print( f'Shape of Test = {Test.shape}' )

/mnt/sdb/home/hongjun/.conda/envs/python38/lib/python3.8/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

Shape of X_Train = (32975653, 38)
Shape of Y_Train = (32975653,)
Shape of Test = (0, 38)

In [15]:
# # 建立決策樹模型
DTC = DecisionTreeClassifier(random_state=42,max_depth=1)

# 自變數、應變數進行擬合
#DTC.fit( X_Train, Y_Train )

# 排序特徵重要性(由大到小)
#col_names = X_Train.columns
#importances = DTC.feature_importances_
#Feature_Rank = pd.DataFrame( { 'Feature_Name':col_names, 'Importance':importances } )
#Feature_Rank.sort_values( by='Importance', ascending=False, inplace=True ) 
#Feature_Rank

In [16]:
# SelectedFeatures = ['dt','trdtp','poscd','domestic_offline_amt_pct','educd','age','chid']

# # txn_amt、slam兩欄小數點似乎過多，要再處理，這邊先直接砍掉
# SelectedFeatures = ['dt', 'chid',  'txn_cnt', 'domestic_offline_cnt',
#        'domestic_online_cnt', 'overseas_offline_cnt', 'overseas_online_cnt',
#        'domestic_offline_amt_pct', 'domestic_online_amt_pct',
#        'overseas_offline_amt_pct', 'overseas_online_amt_pct', 
#        'masts', 'educd', 'trdtp', 'naty', 'poscd', 'cuorg', 
#        'gender_code', 'age']

# 全放
SelectedFeatures = ['dt', 'chid', 'txn_cnt', 'txn_amt', 'domestic_offline_cnt',
       'domestic_online_cnt', 'overseas_offline_cnt', 'overseas_online_cnt',
       'domestic_offline_amt_pct', 'domestic_online_amt_pct',
       'overseas_offline_amt_pct', 'overseas_online_amt_pct', 'sum_card_txn_cnt',
       'card_1_txn_amt_pct', 'card_2_txn_amt_pct', 'card_3_txn_amt_pct',
       'card_4_txn_amt_pct', 'card_5_txn_amt_pct', 'card_6_txn_amt_pct',
       'card_7_txn_amt_pct', 'card_8_txn_amt_pct', 'card_9_txn_amt_pct',
       'card_10_txn_amt_pct', 'card_11_txn_amt_pct', 'card_12_txn_amt_pct',
       'card_13_txn_amt_pct', 'card_14_txn_amt_pct', 'card_other_txn_amt_pct',
       'masts', 'educd', 'trdtp', 'naty', 'poscd', 'cuorg', 'slam',
       'gender_code', 'age', 'primary_card']

In [27]:
DTC.fit( X_Train[SelectedFeatures], Y_Train )

DecisionTreeClassifier(max_depth=1, random_state=42)

In [19]:
pre_X_Train = X_Train[SelectedFeatures].drop_duplicates(subset=['chid'], keep='last')

In [22]:
pre_X_Train.chid.head(10)

14522059    10111801
14522352    10013382
14522623    10464422
14523680    10203945
14525427    10276085
14526247    10225569
14526752    10058090
14533800    10127904
14534326    10470835
14534399    10152646
Name: chid, dtype: int64

In [23]:
test.chid.head(10)

0    10128239
1    10077943
2    10277876
3    10364842
4    10392717
5    10439550
6    10285755
7    10335334
8    10072243
9    10274006
Name: chid, dtype: int64

In [25]:
pre_X_Train1 = pre_X_Train.set_index('chid', drop= False)
pre_X_Train1 = pre_X_Train1.loc[test.chid]

In [26]:
pre_X_Train1

,dt,chid,txn_cnt,txn_amt,domestic_offline_cnt,domestic_online_cnt,overseas_offline_cnt,overseas_online_cnt,domestic_offline_amt_pct,domestic_online_amt_pct,overseas_offline_amt_pct,overseas_online_amt_pct,sum_card_txn_cnt,card_1_txn_amt_pct,card_2_txn_amt_pct,card_3_txn_amt_pct,card_4_txn_amt_pct,card_5_txn_amt_pct,card_6_txn_amt_pct,card_7_txn_amt_pct,card_8_txn_amt_pct,card_9_txn_amt_pct,card_10_txn_amt_pct,card_11_txn_amt_pct,card_12_txn_amt_pct,card_13_txn_amt_pct,card_14_txn_amt_pct,card_other_txn_amt_pct,masts,educd,trdtp,naty,poscd,cuorg,slam,gender_code,age,primary_card
chid,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10128239,24,10128239,2,1.580629e-111,2,0,0,0,1.00,0.00,0.0,0.0,2,0.00,0.0,0.0,0.0,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0,8.0,1.0,1.0,30.0,1.868859e-213,0.0,4.0,1
10077943,24,10077943,2,1.019929e-111,0,0,0,2,0.00,0.00,0.0,1.0,2,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,12.0,1.0,2.0,30.0,8.865641e-214,0.0,5.0,1
10277876,24,10277876,1,3.600542e-112,1,0,0,0,1.00,0.00,0.0,0.0,1,1.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,6.0,1.0,1.0,30.0,8.348441e-214,0.0,0.0,1
10364842,24,10364842,1,3.600542e-112,1,0,0,0,1.00,0.00,0.0,0.0,1,0.00,0.0,0.0,0.0,0.0,0.00,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,5.0,7.0,1.0,99.0,30.0,1.175200e-213,1.0,4.0,1
10392717,24,10392717,1,1.158421e-111,1,0,0,0,1.00,0.00,0.0,0.0,1,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,5.0,1.0,2.0,30.0,4.519731e-214,1.0,2.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10433239,24,10433239,4,1.992041e-111,1,3,0,0,0.25,0.75,0.0,0.0,4,0.75,0.0,0.0,0.0,0.0,0.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,12.0,1.0,1.0,30.0,1.364710e-213,1.0,3.0,1
10235119,24,10235119,2,1.899249e-111,2,0,0,0,1.00,0.00,0.0,0.0,2,0.00,1.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,17.0,1.0,1.0,30.0,1.260870e-213,1.0,4.0,1
10267595,24,10267595,2,1.867759e-111,2,0,0,0,1.00,0.00,0.0,0.0,2,0.00,0.0,1.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,8.0,1.0,2.0,30.0,1.775200e-213,1.0,3.0,1
10160606,24,10160606,1,7.751448e-112,1,0,0,0,1.00,0.00,0.0,0.0,1,0.00,0.0,0.0,1.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,4.0,6.0,1.0,99.0,30.0,1.144558e-213,0.0,5.0,1
10141759,24,10141759,12,2.710763e-111,12,0,0,0,1.00,0.00,0.0,0.0,12,0.00,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,6.0,15.0,1.0,99.0,30.0,1.344194e-213,0.0,2.0,0

In [41]:
predictions = DTC.predict_proba(pre_X_Train1)

In [42]:
best_predictions = np.argsort(predictions, axis=1)[:,-49:]

In [43]:
best_predictions[0]

array([31, 38, 21, 19, 23, 20, 33, 37,  0, 16,  4, 12, 41, 25, 43,  5, 22,
       36, 35,  1, 15, 28, 34, 46, 45,  8, 47, 26, 27, 24,  2, 40, 18,  9,
       13,  3, 32, 14, 44,  7, 17, 10, 42, 29, 48, 11,  6, 39, 30])

In [44]:
best_predictions_final = np.zeros((len(best_predictions), 3), dtype=int)

In [45]:
for a in range(len(best_predictions)):
    sum = 0
    for i in range(49): 
        if (best_predictions[a, i] == [2,6,10,12,13,15,18,19,21,22,25,26,39,37,39,48]).any():
            best_predictions_final[a, sum] = int(best_predictions[a, i])
            sum += 1 
        if sum == 3: 
            break

In [46]:
best_predictions_final[10]

array([21, 19, 39])

In [47]:
len(best_predictions_final)

500000

In [48]:
len(test.chid)

500000

In [49]:
# best_predictions_final =  pd.DataFrame(best_predictions_final)

In [50]:
best_predictions_final

array([[21, 19, 37],
       [21, 19, 39],
       [21, 19, 37],
       ...,
       [21, 19, 37],
       [21, 19, 37],
       [21, 19, 37]])

In [51]:
submission = pd.DataFrame({ 'chid':test.chid,'top1':best_predictions_final[0:len(best_predictions_final),0] , 'top2':best_predictions_final[0:len(best_predictions_final),1] , 'top3':best_predictions_final[0:len(best_predictions_final),2] })

In [52]:
filename = 'submission.csv'
submission.to_csv(filename,index=False)
print(submission)
print('Saved file: ' + filename)

            chid  top1  top2  top3
0       10128239    21    19    37
1       10077943    21    19    39
2       10277876    21    19    37
3       10364842    21    19    37
4       10392717    21    19    37
...          ...   ...   ...   ...
499995  10433239    21    19    37
499996  10235119    21    19    37
499997  10267595    21    19    37
499998  10160606    21    19    37
499999  10141759    21    19    37

[500000 rows x 4 columns]
Saved file: submission.csv